### ISSUE TITLE
Unable to activate the extension VSCode 1.25.0 version.

### ISSUE THREAD

**Issue by tiansin** [kdcro101/vscode-redis#1]
This extension under the Windows VSCode version number for 1.25.0 cannot be activated.

**Comment by kdcro101** [comment]
@tiansin ,

Thank you for your feedback.

To activate `Redis console` choose `Start REDIS console` from command pallete.

P.S. Don't forget to configure server/port/credentials in your workspace settings

**Comment by tiansin** [comment]
vscode-redis/src/workspace/index.ts

`public getSingleRootPath(): string {
        return vscode.workspace.workspaceFolders[0].uri.fsPath;
}`

@kdcro101 I know, because I did not open the workspace, use the command to activate the extension, which will cause the extension engine to report an error, can not activate the extension, it is recommended to add a message prompt, open the workspace and then use **Start REDIS console** command.
