### ISSUE TITLE
Not able to change default port

### ISSUE THREAD

**Issue by albertofilho82** [kdcro101/vscode-redis#2]
Even if I change the default port on  workspace settings, when I go on the command pallete and type "Start Redis Console", it opens back on default port and changes the redis-console.port configuration by itself.

**Comment by kdcro101** [comment]
@albertofilho82 ,

Thank you for your feedback!

Please, update to version `1.0.1`. Problem should be fixed.
Let me know how it went.

If you have any suggestions or bug to report, please, open issue.

**Comment by albertofilho82** [comment]
@kdcro101 
It worked like a charm! Tks a lot!


> @albertofilho82 ,
> 
> Thank you for your feedback!
> 
> Please, update to version `1.0.1`. Problem should be fixed.
> Let me know how it went.
> 
> If you have any suggestions or bug to report, please, open issue.

**Comment by kdcro101** [comment]
Great!

Closing this issue... If you have any problems, open issue!
